blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/FCfyBSbCU5
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/Uniswap/default-token-list#adding-a-token
<<<<<<< HEAD
    about: Any requests to add a token toSabswapshould go here
=======
    about: Any requests to add a token to Uniswap should go here
>>>>>>> 20242fc76106c3e7b5140df5cdf784f98e8d3017
